### ISSUE TITLE
trenches not deleted after deleting modules after saves

### ISSUE THREAD

**Issue by CommandDDOS** [Seb105/Arma-Trencher#2]
repro:
1. place modules to make simple trench
2. save
3. Launch the mission-> trenches are there
4. back do Editor
5. Delete modules, terrain looks fine
6. Save mission again
7. launch the mission -> trenches are still there without modules

expected behaviour: no trenches after deleting modules and saving

**Comment by Seb105** [comment]
Will fix when I've got time. A workaround is to place another trench anywhere on the map, to force the attributes to update.

**Comment by Seb105** [comment]
fixed in 2,0
